// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package pyxis_rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Error
	WatchEvent
	RegisterRequest
	UnRegisterRequest
	PingRequest
	CreateRequest
	DeleteRequest
	StatRequest
	ReadRequest
	WriteRequest
	WatchRequest
	Request
	Response
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrorType int32

const (
	ErrorType_kNone            ErrorType = 0
	ErrorType_kNotLeader       ErrorType = 1
	ErrorType_kNotFound        ErrorType = 2
	ErrorType_kSessionExpired  ErrorType = 4
	ErrorType_kInvalidArgument ErrorType = 5
	ErrorType_kAgain           ErrorType = 6
	ErrorType_kInternal        ErrorType = 7
	ErrorType_kExist           ErrorType = 8
)

var ErrorType_name = map[int32]string{
	0: "kNone",
	1: "kNotLeader",
	2: "kNotFound",
	4: "kSessionExpired",
	5: "kInvalidArgument",
	6: "kAgain",
	7: "kInternal",
	8: "kExist",
}
var ErrorType_value = map[string]int32{
	"kNone":            0,
	"kNotLeader":       1,
	"kNotFound":        2,
	"kSessionExpired":  4,
	"kInvalidArgument": 5,
	"kAgain":           6,
	"kInternal":        7,
	"kExist":           8,
}

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}
func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (x *ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorType_value, data, "ErrorType")
	if err != nil {
		return err
	}
	*x = ErrorType(value)
	return nil
}

type Error struct {
	Type             *ErrorType `protobuf:"varint,1,req,name=type,enum=pyxis.rpc.ErrorType" json:"type,omitempty"`
	Data             []byte     `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetType() ErrorType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ErrorType_kNone
}

func (m *Error) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WatchEvent struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WatchEvent) Reset()         { *m = WatchEvent{} }
func (m *WatchEvent) String() string { return proto.CompactTextString(m) }
func (*WatchEvent) ProtoMessage()    {}

func (m *WatchEvent) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WatchEvent) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type RegisterRequest struct {
	Timeout          *int32 `protobuf:"varint,1,opt,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}

func (m *RegisterRequest) GetTimeout() int32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type UnRegisterRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnRegisterRequest) Reset()         { *m = UnRegisterRequest{} }
func (m *UnRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnRegisterRequest) ProtoMessage()    {}

type PingRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}

type CreateRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Flags            *int32  `protobuf:"varint,2,req,name=flags" json:"flags,omitempty"`
	Data             []byte  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}

func (m *CreateRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CreateRequest) GetFlags() int32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CreateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

func (m *DeleteRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type StatRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}

func (m *StatRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type ReadRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}

func (m *ReadRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type WriteRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}

func (m *WriteRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WriteRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WatchRequest struct {
	Path             *string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Watch            *uint32 `protobuf:"varint,2,opt,name=watch" json:"watch,omitempty"`
	Recursive        *bool   `protobuf:"varint,3,opt,name=recursive" json:"recursive,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}

func (m *WatchRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WatchRequest) GetWatch() uint32 {
	if m != nil && m.Watch != nil {
		return *m.Watch
	}
	return 0
}

func (m *WatchRequest) GetRecursive() bool {
	if m != nil && m.Recursive != nil {
		return *m.Recursive
	}
	return false
}

type Request struct {
	Sid              *uint64            `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	Xid              *uint64            `protobuf:"varint,2,opt,name=xid" json:"xid,omitempty"`
	Register         *RegisterRequest   `protobuf:"bytes,5,opt,name=register" json:"register,omitempty"`
	Unregister       *UnRegisterRequest `protobuf:"bytes,6,opt,name=unregister" json:"unregister,omitempty"`
	Ping             *PingRequest       `protobuf:"bytes,7,opt,name=ping" json:"ping,omitempty"`
	Create           *CreateRequest     `protobuf:"bytes,8,opt,name=create" json:"create,omitempty"`
	Delete           *DeleteRequest     `protobuf:"bytes,9,opt,name=delete" json:"delete,omitempty"`
	Write            *WriteRequest      `protobuf:"bytes,10,opt,name=write" json:"write,omitempty"`
	Read             *ReadRequest       `protobuf:"bytes,11,opt,name=read" json:"read,omitempty"`
	Stat             *StatRequest       `protobuf:"bytes,12,opt,name=stat" json:"stat,omitempty"`
	Watch            *WatchRequest      `protobuf:"bytes,13,opt,name=watch" json:"watch,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *Request) GetXid() uint64 {
	if m != nil && m.Xid != nil {
		return *m.Xid
	}
	return 0
}

func (m *Request) GetRegister() *RegisterRequest {
	if m != nil {
		return m.Register
	}
	return nil
}

func (m *Request) GetUnregister() *UnRegisterRequest {
	if m != nil {
		return m.Unregister
	}
	return nil
}

func (m *Request) GetPing() *PingRequest {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Request) GetCreate() *CreateRequest {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Request) GetWrite() *WriteRequest {
	if m != nil {
		return m.Write
	}
	return nil
}

func (m *Request) GetRead() *ReadRequest {
	if m != nil {
		return m.Read
	}
	return nil
}

func (m *Request) GetStat() *StatRequest {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *Request) GetWatch() *WatchRequest {
	if m != nil {
		return m.Watch
	}
	return nil
}

type Response struct {
	Xid              *uint64     `protobuf:"varint,1,opt,name=xid" json:"xid,omitempty"`
	Err              *Error      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Data             []byte      `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Watch            *WatchEvent `protobuf:"bytes,4,opt,name=watch" json:"watch,omitempty"`
	Sid              *uint64     `protobuf:"varint,5,opt,name=sid" json:"sid,omitempty"`
	Path             *string     `protobuf:"bytes,6,opt,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetXid() uint64 {
	if m != nil && m.Xid != nil {
		return *m.Xid
	}
	return 0
}

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetWatch() *WatchEvent {
	if m != nil {
		return m.Watch
	}
	return nil
}

func (m *Response) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *Response) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func init() {
	proto.RegisterEnum("pyxis.rpc.ErrorType", ErrorType_name, ErrorType_value)
}
