// Code generated by protoc-gen-go.
// source: store/node.proto
// DO NOT EDIT!

/*
Package pyxis_store is a generated protocol buffer package.

It is generated from these files:
	store/node.proto

It has these top-level messages:
	Node
*/
package store

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Node struct {
	Data             []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Children         []string `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
	Flags            *uint32  `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	Version          *uint64  `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Sid              *uint64  `protobuf:"varint,6,opt,name=sid" json:"sid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}

func (m *Node) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Node) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Node) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *Node) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Node) GetSid() uint64 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func init() {
}
