// generated by stringer -type=EventType; DO NOT EDIT

package watch

import "fmt"

const (
	_EventType_name_0 = "NoneCreateDelete"
	_EventType_name_1 = "Modify"
	_EventType_name_2 = "Children"
	_EventType_name_3 = "Connected"
	_EventType_name_4 = "Disconnected"
	_EventType_name_5 = "SessionExpired"
	_EventType_name_6 = "All"
)

var (
	_EventType_index_0 = [...]uint8{4, 10, 16}
	_EventType_index_1 = [...]uint8{6}
	_EventType_index_2 = [...]uint8{8}
	_EventType_index_3 = [...]uint8{9}
	_EventType_index_4 = [...]uint8{12}
	_EventType_index_5 = [...]uint8{14}
	_EventType_index_6 = [...]uint8{3}
)

func (i EventType) String() string {
	switch {
	case 0 <= i && i <= 2:
		lo := uint8(0)
		if i > 0 {
			lo = _EventType_index_0[i-1]
		}
		return _EventType_name_0[lo:_EventType_index_0[i]]
	case i == 4:
		return _EventType_name_1
	case i == 8:
		return _EventType_name_2
	case i == 16:
		return _EventType_name_3
	case i == 32:
		return _EventType_name_4
	case i == 64:
		return _EventType_name_5
	case i == 255:
		return _EventType_name_6
	default:
		return fmt.Sprintf("EventType(%d)", i)
	}
}
